feature-8
wolox-training/ds-java pull request #8
Opened 2021-01-19 19:06 UTC by samuskitchen

## Summary
- Added model user
## Trello Card
https://trello.com/c/MvL5SlgQ/48-git-hooks

2021-01-19 19:35 UTC, Jimenarosello requested changes
Nice job! just a few adjustments :)

2021-01-19 19:35 UTC, Jimenarosello commented on src/main/java/wolox/training/models/User.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
The kind of relationship is many to many, because a user can have many books and a book can be owned by many users :)

2021-01-19 19:35 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +    private User user;
This creates a circular dependency, the user should not be included in the book

2021-01-19 19:35 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +    }
Remember to remove these as well :)

2021-01-19 19:41 UTC, JaimLus commented on src/main/java/wolox/training/models/Book.java
> +    @ManyToOne(fetch = FetchType.LAZY)
So if there is a many-to-one relationship between Book and User that means that a User can have multiple books, but each Book only can have a relation with only one user. Check the specification of the card that ask you that a Book can be in the book collection of more than one User.

2021-01-19 23:21 UTC, samuskitchen commented
I close the PR because there are still card requirements

2021-01-20 17:21 UTC, Jimenarosello approved these changes, later dismissed
Looks good, nice job! 🚀

2021-01-20 18:47 UTC, JaimLus submitted a review, later dismissed
Nice Job

2021-01-20 20:23 UTC, Jimenarosello submitted a review, later dismissed
😊 🚀

2021-01-20 23:00 UTC, JaimLus reviewed
Nice job!

2021-01-20 23:00 UTC, JaimLus commented on src/main/java/wolox/training/controllers/UserController.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> new UserNotFoundException());
Would change () -> new UserNotFoundException() to UserNotFoundException::new

2021-01-20 23:00 UTC, JaimLus commented on src/main/java/wolox/training/controllers/UserController.java
> +        Book book = bookRepository.findById(bookId).orElseThrow(() -> new BookNotFoundException());
Would change () -> new BookNotFoundException() to BookNotFoundException:: new

2021-01-20 23:00 UTC, JaimLus commented on src/main/java/wolox/training/controllers/UserController.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> new UserNotFoundException());
Would change () -> new UserNotFoundException() to UserNotFoundException::new

2021-01-20 23:00 UTC, JaimLus commented on src/main/java/wolox/training/controllers/UserController.java
> +        Book book = bookRepository.findById(bookId).orElseThrow(() -> new BookNotFoundException());
Would change () -> new BookNotFoundException() to BookNotFoundException:: new

2021-01-20 23:00 UTC, JaimLus commented on src/main/java/wolox/training/exceptions/UserIdMismatchException.java
> +}
It's great to think about these cases, but just use the empty constructor.
Personally, I would remove this block of code.

2021-01-20 23:00 UTC, JaimLus commented on src/main/java/wolox/training/exceptions/UserNotFoundException.java
> +    }
Same as previous comment.

2021-01-20 23:00 UTC, JaimLus commented on src/main/java/wolox/training/models/Book.java
> +
I would remove this line blank.

2021-01-20 23:06 UTC, samuskitchen commented on src/main/java/wolox/training/models/Book.java
> +
Sorry my stupid fat toes haha

2021-01-20 23:37 UTC, JaimLus approved these changes
Nice job!

2021-01-21 13:22 UTC, Jimenarosello approved these changes
👏 👏

2021-01-21 13:56 UTC, merged